### ISSUE TITLE
[CK2] Prepare development roadmap for Q2 and Q3 2022

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#189]

**Comment by gfursin** [comment]
Main CM phases for 2022:

- [ ] Develop and stabilize CM core to treat R&D projects as a database of components and automations
- [ ] Document CM core and provide a few tutorials
- [ ] Develop "intelligent components" to detect and/or install all ML artifacts (platform description, OS scripts, ML frameworks, models, data sets, libraries, pre-/post-processing scripts, benchmarks, etc)
  - [ ] Support for ONNX
  - [ ] Support for TVM
  - [ ] Support for PyTorch
  - [ ] Support for TF
  - [ ] Support for TFLite
- [ ] Convert our old CK-based MLPerf inference vision benchmark automations using CM
- [ ] Implement CM-based "experiment" automation (record/reproduce/compare/visualize)
- [ ] Implement CM-based MLPerf Design Space Explorer for open division submissions
- [ ] Use CM to modularize MLCube for MLPerf DSE
- [ ] Convert all MLPerf inference reference benchmarks to CM

**Comment by gfursin** [comment]
Since we have stabilized the [CM (CK2) framework](https://github.com/mlcommons/ck/tree/master/cm) and added CM scripts to [automate ML Systems benchmarking](), we can now work on decomposing MLPerf inference benchmark into these CM scripts and automating the submission: https://github.com/mlcommons/ck/issues/261 .
