### ISSUE TITLE
[CK2/CM scripts] support for ML frameworks and main ToDos

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#245]
- [x] Add readme.md in a script to describe limitations (such as in TF)
- [x] Check that we delete local env inside dependencies loop
- [x] Add -enable_if_env flag and --skip_if_env in script automation similar to CK
- [x] Detect TF via Python first; check version ranges; and install only if missing ...
- [x] Check virtual env creation based on Python dependency as a script (can env be automated?)
- [x] Check caching of deps: https://github.com/mlcommons/ck/issues/248 
- [x] Fix contamination of ENV when detecting/installing artifacts
- [x] ~~Should we do get/install as variation?~~ Possible but we keep it for later if needed by the community
- [x] Check that can add extra tags from Python (including virtual + user tags) to other scripts with Python dependency 
- [x] Check detect/install of ONNX-RT, PyTorch, TVM, Transformers
- [ ] Add basic MLPerf image classification benchmark workflow (onnv/pytorch/tf/tvm)
   - [ ] Add Docker container for this implementation
- [x] Add "cm show cache" (print tags, new ENV, versions from ENV)
- [x] Add dummy "cm test script"
- [x] Add "cm info" to get the {automation UID}::{artifact UID} for a given CM artifact
- [x] Test "get-gcc" with corner detection script
  - [x] See issue when both GCC and LLVM are detected: https://github.com/mlcommons/ck/issues/246
  - [x] Separate compile and run scripts
- [ ] Add support for Android devices and test corner detection
- [ ] Check platform.init scripts from CK (Android and other devices)
- [ ] Add script for CUDA detection
  - [ ] Check that can work with different ranges of GCC versions on Linux
  - [x] Create a simple script to detect CUDA capabilities (compile)
- [x] Rename mcommons@cm-devops to cm-mlops ?
- [ ] Agree how to create "cm test script"
- [x] Move stable scripts to mlcommons@cm-mlops when ready ...
- [ ] ~~Update docs, architecture and basic tutorial~~: Moved to https://github.com/mlcommons/ck/issues/256

**Comment by gfursin** [comment]
Most of the tasks are completed here. I close this ticket and will add new tasks as separate issues.
